##                              AMAZON SALES DATA ANALYSIS 
----------------------------------------------------------------------------------------------------------------
-- OBJECTIVE:The major aim of this project is to gain insight into the sales data of Amazon to 
--    understand the different factors that affect sales of the different branches. -----------------------
use capstone;
select * from amazon;

select `Unit price` from amazon;
select rating from amazon where rating>9;
    
-- modifying column names and data types
ALTER TABLE amazon
   CHANGE  `Invoice ID` Invoice_ID  varchar(30) Not null primary Key,
   MODIFY Branch  varchar (5) not null,
   MODIFY City varchar (30) not null,
   CHANGE `Customer type` Customer_Type varchar (30) not null,
   MODIFY Gender  varchar(10) not null,
   CHANGE `Product line` Product_Line varchar (100) not null,
   CHANGE `Unit price` Unit_Price  decimal(10,2) not null,
   MODIFY Quantity int not null,
   CHANGE `Tax 5%` VAT  float(6,4) not null,
   MODIFY Total decimal (10,4) not null,
   MODIFY Date DATE not null,
   MODIFY Time TIME not null,
   CHANGE `Payment` Payment_Method varchar (15)  not null, 
   MODIFY cogs  decimal (10, 2) not null,
   CHANGE `gross margin percentage` Gross_Margin_Percentage float (11,9) not null,
   CHANGE `gross income` Gross_Income decimal(12, 4) not null,
   MODIFY Rating decimal(3,1) not null;
   
SELECT
    SUM(CASE WHEN Branch IS NULL THEN 1 ELSE 0 END) AS column1_null_count,
    SUM(CASE WHEN City IS NULL THEN 1 ELSE 0 END) AS column2_null_count
    from amazon;
    
 SELECT * FROM amazon;
 describe amazon;

-- ****************************************************************** --
-- PRODUCT ANALYSIS:

SELECT Product_Line,COUNT(*) AS Total_Products,
ROUND(SUM(Total),2) AS Total_revenue,SUM(Quantity) AS Total_Quantity,
ROUND(AVG(Rating),2) AS Average_Rating FROM amazon 
GROUP BY Product_line ORDER BY Average_Rating DESC;
/*Food and beverages has the highest average rating and generated highest revenue among 
all product lines.Home and lifestyle products have the lowest average rating.
Health and beauty products has the lowest revenue and total quantity sold*/

 -- SALES ANALYSIS:
 
 -- What are the overall sales trends over different time periods (weekly, monthly)?

SELECT MONTH,Week_Number, Weekly_Total_Sales,
ROW_NUMBER() OVER (PARTITION BY MONTH ORDER BY Week_Number) AS Week_row
FROM(SELECT EXTRACT(MONTH FROM Date) AS Month,
           EXTRACT(WEEK FROM Date) AS Week_Number,
           SUM(Total) AS Weekly_Total_Sales
FROM amazon GROUP BY Month, Week_Number) as  Weekly_Sales
ORDER BY weekly_total_sales DESC;
/*Total_sales in 1st week of each month is lower */

SELECT MONTH(Date) AS Month, SUM(Total) AS monthly_Total_Sales
FROM amazon GROUP BY Month ORDER BY monthly_total_sales desc;
/* Jaunuary month recorded highest revenue of 116291.8680 */

SELECT Branch,city,SUM(Total) AS Total_Sales
FROM amazon GROUP BY Branch,city
ORDER BY Total_Sales DESC;
/*Naypyitaw is  top-performing branch in terms of revenue, Yangon and Mandalay are not far behind */
    
SELECT Payment_method,SUM(Total) AS Channel_Revenue,
SUM(Total) / (SELECT SUM(Total) FROM amazon) * 100 AS Contribution_Percentage
FROM amazon  GROUP BY Payment_method ORDER BY Channel_Revenue DESC;
/*The data reveals that cash payments contribute the highest percentage (34.74%) to the total revenue,
 followed closely by payments made through e-wallets (34.06%).Credit card payments have the lowest 
 contribution percentage (31.20%). */
 
 
-- CUSTOMER ANALYSIS:

--  distribution of customers across segments and revenue generated 
SELECT Customer_Type,Gender,COUNT(*) AS customer_count,SUM(Total) as Revenue  
FROM amazon GROUP BY Customer_Type,Gender;
/* The distribution of male and female customers across customer types is almost equal,yet the revenue
 generated by female customers significantly surpasses that of male customers within each customer type */

-- product_lines which generating highest profit based on different customer segments
select product_line,customer_type,sum(gross_income)as profit from amazon 
group by product_line,customer_type order by profit desc;

-- ******************************************************************* 
-- ***************************FEATURE ENGINEERING******************************
-- Adding a new column named timeofday to give insight of sales in the Morning, Afternoon and Evening.  
SELECT TIME FROM amazon;
SELECT Time,(CASE 
				WHEN time BETWEEN "00:00:00" AND "11:59:59" THEN "MORNING"
                WHEN time BETWEEN "12:00:00" AND "15:59:59" THEN "AFTERNOON"
                ELSE "EVENING" END )AS Time_of_day 
                FROM amazon;
ALTER TABLE amazon ADD COLUMN Time_of_day VARCHAR(20);
UPDATE 	amazon SET Time_of_day=(CASE 
                                   WHEN time BETWEEN "00:00:00" AND "11:59:59" THEN "MORNING"
                                   WHEN time BETWEEN "12:00:00" AND "15:59:59" THEN "AFTERNOON"
                                   ELSE "EVENING" END );
set SQL_SAFE_UPDATES=0;
SELECT * FROM amazon;
 
-- Adding  a new column named dayname that contains the extracted days of the week on which the given transaction took place  
SELECT Date,dayname(Date) FROM amazon;
ALTER TABLE amazon ADD COLUMN Day_Name VARCHAR(10);
UPDATE amazon SET Day_Name=dayname(Date);

--  Adding a new column named monthname that contains the extracted months of the year on which the given transaction took place 
 SELECT Date,month(Date) from amazon;
 ALTER TABLE amazon ADD COLUMN Month_Name VARCHAR(10);
 UPDATE amazon SET Month_name=monthname(Date);
 
 -- ****************************BUSINESS QUESTIONS*****************************
 SELECT * FROM amazon;

-- 1)What is the count of distinct cities in the dataset?
SELECT count(DISTINCT City) FROM amazon;
/* There are 3 distinct cities in the data i.e Yangon,Naypyitaw,Mandalay */

-- 2)For each branch, what is the corresponding city?
SELECT DISTINCT Branch,City FROM amazon;
/* Correspoinding city for each branch are A,B,C*/

-- 3)What is the count of distinct product lines in the dataset?
SELECT COUNT(DISTINCT Product_line) from amazon;
/*There are total 6 distinct product_lines are there in data*/

-- 4)Which payment method occurs most frequently?
 SELECT Payment_method,COUNT(Payment_Method) AS count_pm FROM amazon GROUP BY Payment_Method 
 ORDER BY count_pm DESC;
 /* EWallet is the most frequent payment method with count of 345*/
 
 -- 5)Which product line has the highest sales?
SELECT Product_Line,SUM(quantity) as total_sales FROM amazon GROUP BY Product_Line
 ORDER BY total_sales DESC ;
 /*electronic accessories recorded highest sales   */
 
 -- 6)How much revenue is generated each month?
 SELECT Month_Name AS Month,SUM(Total) AS Total_revenue FROM amazon GROUP BY Month
 ORDER BY Total_revenue DESC;
 /* Jaunuary revenue is 116291.8680..*/
 
 -- 7)In which month did the cost of goods sold reach its peak?
 SELECT Month_Name AS Month,SUM(cogs) AS cost_of_goods FROM amazon GROUP BY Month
 ORDER BY cost_of_goods  DESC LIMIT 1;
 /* Jaunuary cogs sum with peack of 110754.16*/
 
 -- 8)Which product line generated the highest revenue?
 SELECT Product_Line,SUM(Total) AS Sales FROM amazon GROUP BY Product_Line ORDER BY Sales DESC LIMIT 1;
 /* food and beverages with sales amount of 56144.8440 */
 
 -- 9)In which city was the highest revenue recorded?
 SELECT City,SUM(Total) AS Revenue FROM amazon GROUP BY City ORDER BY Revenue DESC LIMIT 1;
/*Naypyitaw city with higest revenue of 110568.7065*/

-- 10)Which product line incurred the highest Value Added Tax?
SELECT Product_Line,SUM(VAT) AS VAT_sum FROM amazon GROUP BY Product_Line 
ORDER BY VAT_sum DESC LIMIT 1;
/*Food and beverages with higest sum of 2673.5640 */

-- 11)For each product line, add a column indicating "Good" if its sales are above average, otherwise "Bad."
  SELECT Product_Line,avg(quantity) AS Avg_quantity,CASE 
                        WHEN  avg(quantity) > (SELECT AVG(Quantity) FROM amazon) THEN 'GOOD'
                        ELSE 'BAD' END AS Sales_status
FROM amazon GROUP BY Product_Line;
  
  /*SELECT Product_Line, 
    CASE 
        WHEN sum(total) > (SELECT AVG(total) FROM amazon) THEN 'Good'
        ELSE 'Bad'END AS Sales_status
  FROM amazon GROUP BY Product_Line;
  
  SELECT product_line,total,CASE 
  WHEN Total > (SELECT AVG(Total)  FROM amazon as avg_sales where avg_sales.product_line=amazon.product_line)
  THEN "GOOD" ELSE "BAD"
  END AS SALES_STATUS FROM amazon; */
   
  select * from amazon;
  
-- 12)Identify the branch that exceeded the average number of products sold.
SELECT Branch,SUM(Quantity) AS TotalQuantity, (SELECT round(AVG(TotalQuantity)) FROM 
(SELECT SUM(Quantity) AS TotalQuantity FROM amazon GROUP BY Branch) AS subquery) AS AverageQuantity
FROM amazon GROUP BY Branch
HAVING SUM(Quantity) > averagequantity;
/*Branch A exceeded the average quantity with total quantity of 1859*/ 

-- 13)Which product line is most frequently associated with each gender?
SELECT Gender,Product_line,Frequency
FROM (SELECT Gender,Product_line,COUNT(*) AS Frequency,
        ROW_NUMBER() OVER (PARTITION BY Gender ORDER BY COUNT(*) DESC) AS Ranked
    FROM amazon GROUP BY Gender,Product_line
) AS RankedData WHERE Ranked = 1;
/* "Fashion accessories" is the product line most frequently associated with females,
 while "Health and beauty" is the product line most frequently associated with males. */
 
-- 14)Calculate the average rating for each product line.
SELECT Product_Line,ROUND(AVG(Rating),1) AS Rating_avg FROM amazon GROUP BY Product_Line
ORDER BY Rating_avg DESC;
/*Food and beverages with highest average rating of 7.1 and Home and lifestyle with least rating of 6.8*/

-- 15)Count the sales occurrences for each time of day on every weekday.
select * from amazon;
SELECT  Day_Name ,Time_OF_Day,COUNT(*) AS Frequency  FROM amazon 
WHERE DAYOFWEEK(Date) BETWEEN 2 AND 6 GROUP BY Time_OF_Day, Day_name ORDER BY Frequency DESC;

-- 16)Identify the customer type contributing the highest revenue.
SELECT Customer_Type,SUM(Total) as revenue FROM amazon GROUP BY Customer_Type 
ORDER BY revenue DESC;
/* Members generating high revenue*/

-- 17)Determine the city with the highest VAT percentage.
SELECT City,MAX(VAT) AS VAT_Value FROM amazon GROUP BY City ORDER BY MAX(VAT) DESC;
/*SELECT City,(MAX(VAT)/MAX(Total))*100 AS VAT_pct FROM amazon GROUP BY City 
ORDER BY VAT_pct DESC LIMIT 3;

SELECT City,(SUM(VAT)/SUM(Total))*100 AS VAT_pct FROM amazon
GROUP BY City ORDER BY VAT_pct DESC LIMIT 3;*/
 
-- 18)Identify the customer type with the highest VAT payments.
SELECT Customer_Type,SUM(VAT) AS VAT_sum FROM amazon GROUP BY Customer_Type
ORDER BY VAT_sum DESC LIMIT 1;
/* Member */

-- 19)What is the count of distinct customer types in the dataset?
SELECT DISTINCT(Customer_Type) as Customer_Type,COUNT(*) AS Dist_customers_count 
FROM amazon GROUP BY Customer_Type;
/* There are 2 distinct customer types in data i.e member and normal */

-- 20)What is the count of distinct payment methods in the dataset?
SELECT DISTINCT (Payment_Method) as payment_method ,COUNT(*) AS Payment_Count 
FROM amazon GROUP BY Payment_Method;
/* There are 3 distinct Payment_methods in dataset i.e Ewallet,Cash and Credit card */

-- 21)Which customer type occurs most frequently?
 SELECT Customer_Type,COUNT(*) AS Frequency FROM amazon GROUP BY Customer_Type
ORDER BY COUNT(*) DESC LIMIT 1;
/* The customer type "Member" occurs most frequently with a count of 501 occurrences */

-- 22)Identify the customer type with the highest purchase frequency.
SELECT Customer_Type,COUNT(*) AS Purchase_Frequency ,SUM(Quantity) AS Total_quantity,
SUM(Total) as Money_spent FROM amazon
GROUP BY Customer_Type ORDER BY Purchase_Frequency DESC ;
/* The customer type "Member" occurs most frequently with a count of 501 occurrences and
 with total amount of 164223.4440*/

-- 23)Determine the predominant gender among customers.
SELECT Gender,COUNT(Gender) as predominant_gender FROM amazon
GROUP BY Gender ORDER BY predominant_gender DESC LIMIT 1;
/*The predominant gender among customers is Female, with 501 occurrences */
  
-- 24)Examine the distribution of genders within each branch.
SELECT Branch,Gender,COUNT(Gender) AS gender_count FROM amazon 
GROUP BY Branch,Gender ORDER BY Branch;
/*In branch A, there are 161 females and 179 males. In branch B,
 there are 162 females and 170 males. In branch C, there are 178 females and 150 males */

-- 25)Identify the time of day when customers provide the most ratings.
SELECT Time_of_day,COUNT(rating) AS Rating_count FROM amazon GROUP BY time_of_day
 ORDER BY Rating_count DESC;
 /* In the evening Rating_count is high with count of 432 */
 
 -- 26)Determine the time of day with the highest customer ratings for each branch.
 SELECT Time_Of_Day, Branch, Customer_rating FROM (
 SELECT Time_Of_Day, Branch,AVG(Rating) AS Customer_rating,
 RANK() OVER (PARTITION BY Branch ORDER BY AVG(Rating) DESC) AS ranked_rating
 FROM amazon GROUP BY Time_Of_Day, Branch ) AS avg_ranking WHERE ranked_rating=1;
 /* The average highest customer rating for Branch A is 7.18 in the Afternoon, for 
 Branch B it is 6.89 in the Morning, and for Branch C, it is 7.11 in the Evening. */
 
 -- 27)Identify the day of the week with the highest average ratings.
 SELECT Day_Name,ROUND(AVG(Rating),1) AS avg_rating  FROM amazon
 GROUP BY Day_Name ORDER BY avg_rating DESC LIMIT 1;
 /* Monday is the day with highest average rating of 7.1 */
 
 -- 28)Determine the day of the week with the highest average ratings for each branch.
 SELECT Day_Name,Branch,Customer_rating FROM(
 SELECT Day_Name,Branch,AVG(Rating) AS Customer_rating,
 ROW_NUMBER() OVER (PARTITION BY Branch ORDER BY AVG(Rating) DESC) AS rank_rate
 FROM amazon GROUP BY Day_Name,Branch) AS rating_avg WHERE rank_rate=1;
 /* The average highest customer rating for Branch A is 7.31 on  Friday, for 
 Branch B it is 7.33 on Monday, and for Branch C it is 7.27 on Friday */ 
  
